<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectTable extends Doctrine_Table
{
  public function construct()
  {
    $this->setOption('orderBy', 'name ASC');
  }
  
  public function findByProductQuery($product) {
    $q = $this->createQuery('p')
      ->where('p.product_id = ?', $product->getId());
    return $q;
  }
}