<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StoryTable extends Doctrine_Table
{
  public function findByProduct($product) {
    $q = $this->createQuery('s')
      ->leftJoin('s.Iteration i')
      ->leftJoin('i.Project p')
      ->where('p.product_id = ?', $product->getId());

    return $q->execute();
  }

  public function findByProject($project) {
    $q = $this->createQuery('s')
      ->leftJoin('s.Iteration i')
      ->where('i.project_id = ?', $project->getId());

    return $q->execute();
  }

  public function findByIterationQuery($iteration) {
    $q = $this->createQuery('s')
      ->where('s.iteration_id = ?', $iteration->getId())
      ->orderBy('s.priority DESC');
    return $q;
  }

  public function findByIteration($iteration) {
    return $this->findByIterationQuery($iteration)->execute();
  }
}