<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TeamTable extends Doctrine_Table
{
  public function findAvailable(UserProfile $userProfile) {
    $q = $this->createQuery('t')
      ->where('NOT EXISTS (SELECT * FROM UserPerTeam upt WHERE upt.user_id = ? and upt.team_id = t.id)', $userProfile->getId());

    return $q->execute();
  }

}