<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserProfile extends BaseUserProfile
{
  public function getFullName() {
    $fullname = $this->getFirstName() . ' ' . $this->getLastName();
    if(trim($fullname) == '')
      return $this->getUsername();
    
    return $fullname;
  }

  public function getRoles() {
    return $this->getUser()->getGroups();
  }

  public function getUserName() {
    return $this->getUser()->getUserName();
  }

  public function getLastLogin() {
    $lastLogin = $this->getUser()->getLastLogin();
    if(!empty($lastLogin))
      $lastLogin;
    return 'Never logged in';
  }

  public function getGroups() {
    return $this->getUser()->getGroups();
  }

  public function addTeam(Team $team) {
    $this->Teams[] = $team;
    $this->save();
  }

  public function removeTeam(Team $team) {
    $this->unlink('Teams', array($team->getId()));
  }

  public function getAvailableTeams() {
    return Doctrine::getTable('Team')->findAvailable($this);
  }

  public function delete(Doctrine_Connection $conn = null)
  {
    $this->getUser()->delete();
    return parent::delete($conn);
  }

  public function getPicture() {
    $url = $this->getPictureUrl();
    if($url == "")
      return '/images/no_photo.png';

    return '/uploads/pictures/' . $url;
  }
}