<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserProfileTable extends Doctrine_Table
{
  public function findAvailable(Team $team) {
    $q = $this->createQuery('u')
      ->where('NOT EXISTS (SELECT * FROM UserPerTeam upt WHERE upt.team_id = ? and upt.user_id = u.id)', $team->getId());

    return $q->execute();
  }
  
  public function findAllOrdered() {
    $q = $this->createQuery()
      ->orderBy('Email ASC');
      
    return $q->execute();
  }
}