<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Product extends BaseProduct
{
  public function getIterations() {
    return Doctrine::getTable('Iteration')->findByProduct($this);
  }

  public function getStories() {
    return Doctrine::getTable('Story')->findByProduct($this);
  }

  public function getTasks() {
    return Doctrine::getTable('Task')->findByProduct($this);
  }
}