<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Story extends BaseStory
{
  public function getProduct() {
    return $this->getIteration()->getProduct();
  }

  public function getProject() {
    return $this->getIteration()->getProject();
  }

  public function getTasks() {
    return Doctrine::getTable('Task')->findByStory($this);
  }

  public function countTasks() {
    return Doctrine::getTable('Task')->countByStory($this);
  }

  public function countAvailableTasks() {
    return Doctrine::getTable('Task')->countAvailableByStory($this);
  }

  public function getEffortLeft() {
    $timestamp = 0;
    foreach($this->getTasks() as $task)
      $timestamp += $task->getEffortLeft();
    return $timestamp;
  }

  public function getOriginalEstimate() {
    $timestamp = 0;
    foreach($this->getTasks() as $task)
      $timestamp += $task->getOriginalEstimate();
    return $timestamp;
  }

  public function getCurrentEstimate() {
    $timestamp = 0;
    foreach($this->getTasks() as $task)
      $timestamp += $task->getCurrentEstimate();
    return $timestamp;
  }

  public function getEffortSpent() {
    $timestamp = 0;
    foreach($this->getTasks() as $task)
      $timestamp += $task->getEffortSpent();
    return $timestamp;
  }
}