<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/03/01 07:44:39
$this->security = array (
  'secure' => 
  array (
    'is_secure' => 'off',
  ),
  'signin' => 
  array (
    'is_secure' => 'off',
    'require_ssl' => true,
  ),
  'signout' => 
  array (
    'is_secure' => 'off',
    'require_ssl' => true,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
