<?php

/**
 * BaseBacklogTask
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $project_id
 * @property string $name
 * @property string $description
 * @property integer $estimate
 * @property enum $priority
 * @property Project $Project
 * 
 * @method integer     getProjectId()   Returns the current record's "project_id" value
 * @method string      getName()        Returns the current record's "name" value
 * @method string      getDescription() Returns the current record's "description" value
 * @method integer     getEstimate()    Returns the current record's "estimate" value
 * @method enum        getPriority()    Returns the current record's "priority" value
 * @method Project     getProject()     Returns the current record's "Project" value
 * @method BacklogTask setProjectId()   Sets the current record's "project_id" value
 * @method BacklogTask setName()        Sets the current record's "name" value
 * @method BacklogTask setDescription() Sets the current record's "description" value
 * @method BacklogTask setEstimate()    Sets the current record's "estimate" value
 * @method BacklogTask setPriority()    Sets the current record's "priority" value
 * @method BacklogTask setProject()     Sets the current record's "Project" value
 * 
 * @package    nubee
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseBacklogTask extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('backlog_task');
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('estimate', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('priority', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => 'none',
              1 => 'p1',
              2 => 'p2',
              3 => 'p3',
              4 => 'p4',
              5 => 'p5',
              6 => 'p6',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}