all:
  doctrine:
    class:        sfDoctrineDatabase
    param:
      username:   nubeeadmin
      password:   db@dmin1
      charset:    utf8
      encoding:   utf8

prod:
  doctrine:
    param:
      dsn:        'mysql:host=localhost;dbname=nubee_prod'

preprod:
  doctrine:
    param:
      dsn:        'mysql:host=localhost;dbname=nubee_prod'

dev:
  doctrine:
    param:
      dsn:        'mysql:host=localhost;dbname=nubee_dev'

test:
  doctrine:
    param:
      dsn:        'mysql:host=localhost;dbname=nubee_test'
