<?php

/**
 * BaseProjectRelation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $parent_id
 * @property integer $child_id
 * @property Project $Parent
 * @property Project $Child
 * 
 * @method integer         getParentId()  Returns the current record's "parent_id" value
 * @method integer         getChildId()   Returns the current record's "child_id" value
 * @method Project         getParent()    Returns the current record's "Parent" value
 * @method Project         getChild()     Returns the current record's "Child" value
 * @method ProjectRelation setParentId()  Sets the current record's "parent_id" value
 * @method ProjectRelation setChildId()   Sets the current record's "child_id" value
 * @method ProjectRelation setParent()    Sets the current record's "Parent" value
 * @method ProjectRelation setChild()     Sets the current record's "Child" value
 * 
 * @package    nubee
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
abstract class BaseProjectRelation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project_relation');
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('child_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project as Parent', array(
             'local' => 'parent_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Project as Child', array(
             'local' => 'child_id',
             'foreign' => 'id'));
    }
}