<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UpdateStoryTable extends Doctrine_Migration
{
	public function up()
	{
    $this->addColumn('story', 'priority', 'enum', array(
      'notnull' => true,
      'values' => array('none', 'p1', 'p2', 'p3', 'p4', 'p5'),
      'default' => 'none'));
	}

	public function down()
	{
    $this->removeColumn('story', 'priority');
	}
}