<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddWiki extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('bl_wiki_page', array(
      'id' => array(
      'type' => 'integer',
      'length' => 8,
      'primary' => true,
      'autoincrement' => true,
      ),
      'title' =>
      array(
      'type' => 'string',
      'length' => 255,
      'notnull' => true,
      ),
      'content' =>
      array(
      'type' => 'string',
      'notnull' => true,
      'length' => 2147483647,
      ),
      'revision' =>
      array(
      'type' => 'integer',
      'length' => 8,
      'notnull' => true,
      ),
      'creator_id' =>
      array(
      'type' => 'integer',
      'length' => 8,
      ),
      'editor_id' =>
      array(
      'type' => 'integer',
      'length' => 8,
      ),
      'created_at' =>
      array(
      'type' => 'timestamp',
      'length' => 25,
      ),
      'updated_at' =>
      array(
      'type' => 'timestamp',
      'length' => 25,
      ),
      'slug' =>
      array(
      'type' => 'string',
      'length' => 255,
      ),
      ), array(
      'indexes' =>
      array(
      ),
      'primary' =>
      array(
      0 => 'id',
      ),
    ));
    $this->createTable('bl_wiki_page_revision', array(
      'page_id' =>
      array(
      'type' => 'integer',
      'length' => 8,
      'primary' => true,
      ),
      'revision' =>
      array(
      'type' => 'integer',
      'length' => 8,
      'primary' => true,
      ),
      'title' =>
      array(
      'type' => 'string',
      'length' => 255,
      'notnull' => true,
      ),
      'content' =>
      array(
      'type' => 'string',
      'notnull' => true,
      'length' => 2147483647,
      ),
      'editor_id' =>
      array(
      'type' => 'integer',
      'length' => 8,
      ),
      'updated_at' =>
      array(
      'type' => 'timestamp',
      'length' => 25,
      ),
      ), array(
      'indexes' =>
      array(
      ),
      'primary' =>
      array(
      0 => 'page_id',
      1 => 'revision',
      ),
    ));
	}

	public function down()
	{
		$this->dropTable('bl_wiki_page');
		$this->dropTable('bl_wiki_page_revision');
	}
}