<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductTable extends Doctrine_Table
{
  public function construct()
  {
    $this->setOption('orderBy', 'name ASC');
  }
}