# These settings are parameters for the adLDAP library.  See
# its code (plugins/bhLDAPAuthPlugin/lib/adLDAP.php) and documentation
# (http://adldap.sourceforge.net) for help.
adLDAP:

  # the AD domain's name
  account_suffix      :  "@domain.com"

  # base for all users and groups
  base_dn             :  "ou=People,dc=domain,dc=com"

  # An array of domain controllers. Specify multiple controllers if you 
  # would like the class to balance the LDAP queries amongst multiple servers
  domain_controllers:
    - 
    - 

  ad_username: ldapreader
  ad_password: ldapreader

groupMappings:
  Developer:
    - Domain Admins
    - Power Users
    - Domain Users
  Manager:
    - Domain Admins
    - Power Users
  Administrator:
    - Domain Admins
