<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/03/01 07:45:57

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'username' => 'nubeeadmin',
  'password' => 'db@dmin1',
  'charset' => 'utf8',
  'encoding' => 'utf8',
  'dsn' => 'mysql:host=localhost;dbname=nubee_prod',
  'name' => 'doctrine',
)),);
