<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/03/01 07:45:57
sfConfig::add(array(
  'app_sf_guard_plugin_check_password_callable' => array (
  0 => 'bhLDAP',
  1 => 'checkPassword',
),
));
