<?php

/**
 * BaseProjectMember
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $project_id
 * @property integer $member_id
 * @property Project $Project
 * @property sfGuardUser $Member
 * 
 * @method integer       getProjectId()  Returns the current record's "project_id" value
 * @method integer       getMemberId()   Returns the current record's "member_id" value
 * @method Project       getProject()    Returns the current record's "Project" value
 * @method sfGuardUser   getMember()     Returns the current record's "Member" value
 * @method ProjectMember setProjectId()  Sets the current record's "project_id" value
 * @method ProjectMember setMemberId()   Sets the current record's "member_id" value
 * @method ProjectMember setProject()    Sets the current record's "Project" value
 * @method ProjectMember setMember()     Sets the current record's "Member" value
 * 
 * @package    nubee
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjectMember extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project_member');
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('member_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}