<?php

/**
 * BaseProjectMember
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $project_id
 * @property integer $member_id
 * 
 * @method integer       getProjectId()  Returns the current record's "project_id" value
 * @method integer       getMemberId()   Returns the current record's "member_id" value
 * @method ProjectMember setProjectId()  Sets the current record's "project_id" value
 * @method ProjectMember setMemberId()   Sets the current record's "member_id" value
 * 
 * @package    nubee
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjectMember extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project_member');
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('member_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}