<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UpdateTaskTable extends Doctrine_Migration
{
	public function up()
	{
    $this->addColumn('task', 'description', 'string');
    $this->changeColumn('task', 'effort_spent', 'integer', array(
      'notnull' => true));
    $this->changeColumn('task', 'estimate', 'integer', array(
      'notnull' => true));
    $this->changeColumn('task', 'effort_left', 'integer', array(
      'notnull' => true));
	}

	public function down()
	{
    $this->removeColumn('task', 'description');
    $this->changeColumn('task', 'effort_spent', 'string', array(
      'notnull' => true,
      'length' => 5));
    $this->changeColumn('task', 'estimate', 'string', array(
      'notnull' => true,
      'length' => 5));
    $this->changeColumn('task', 'effort_left', 'string', array(
      'notnull' => true,
      'length' => 5));
	}
}