<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddDescriptions extends Doctrine_Migration
{
	public function up()
	{
    $this->addColumn('iteration', 'description', 'string');
    $this->addColumn('story', 'description', 'string');
	}

	public function down()
	{
    $this->removeColumn('iteration', 'description');
    $this->removeColumn('story', 'description');
	}
}