<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApplyWorkingUnitForeignKeyConstraints extends Doctrine_Migration
{
	public function up()
	{
    $this->createForeignKey('working_unit', array(
      'local' => 'user_id',
      'foreign' => 'id',
      'foreignTable' => 'sf_guard_user',
      'name' => 'working_unit_user_id',
      'onDelete' => 'CASCADE'
    ));
    $this->createForeignKey('working_unit', array(
      'local' => 'task_id',
      'foreign' => 'id',
      'foreignTable' => 'task',
      'name' => 'working_unit_task_id',
      'onDelete' => 'CASCADE'
    ));
	}

	public function down()
	{
		$this->dropForeignKey('working_unit', 'working_unit_user_id');
		$this->dropForeignKey('working_unit', 'working_unit_task_id');
	}
}