<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddWorkingUnits extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('working_unit', array(
      'id' => array(
        'type' => 'integer',
        'length' => 20,
        'autoincrement' => true,
        'primary' => true,
      ),
      'user_id' => array(
        'type' => 'integer',
        'notnull' => true,
        'length' => 2147483647,
      ),
      'task_id' => array(
        'type' => 'integer',
        'notnull' => true,
        'length' => 2147483647,
      ),
      'effort_left' => array(
        'type' => 'integer',
        'notnull' => true,
        'length' => 2147483647,
      ),
      'created_at' => array(
        'type' => 'timestamp',
        'length' => 25,
      ),
      'updated_at' => array(
        'type' => 'timestamp',
        'length' => 25,
      )
    ), array(
      'indexes' => array(),
      'primary' => array(0 => 'id')
    ));
	}

	public function down()
	{
    $this->dropTable('wokring_unit');
	}
}