<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('sf_guard_user', 'first_name', 'string', '255', array(
             ));
        $this->addColumn('sf_guard_user', 'last_name', 'string', '255', array(
             ));
        $this->addColumn('sf_guard_user', 'email_address', 'string', '255', array(
             'notnull' => '1',
             'unique' => '1',
             ));
        $this->changeColumn('sf_guard_remember_key', 'ip_address', 'string', '50', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('sf_guard_user', 'first_name');
        $this->removeColumn('sf_guard_user', 'last_name');
        $this->removeColumn('sf_guard_user', 'email_address');
    }
}