<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('iteration', 'end_date', 'date', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('task', 'user_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('iteration', 'end_date');
        $this->removeColumn('task', 'user_id');
    }
}