<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/11/08 22:27:52
$this->security = array (
  'home' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
