<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/10/13 18:52:33
$this->security = array (
  'home' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
