<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Iteration extends BaseIteration
{
  public function getProduct() {
    return $this->getProject()->getProduct();
  }
  
  public function getManager() {
    return $this->getProject()->getManager();
  }  
  
  public function hasMembers() {
    return $this->getMembers()->count() > 0;
  }  
  
  public function getMembers() {
    return $this->getProject()->getMembers();
  }  
  
  public function getTasks() {
    return Doctrine::getTable('Task')->findByIteration($this);
  }

  public function countTasks() {
    return Doctrine::getTable('Task')->countByIteration($this);
  }

  public function countAvailableTasks() {
    return Doctrine::getTable('Task')->countAvailableByIteration($this);
  }

  public function getStories() {
    return Doctrine::getTable('Story')->findByIteration($this);
  }

  public function getEffortLeft() {
    $timestamp = 0;
    foreach($this->getTasks() as $task)
      $timestamp += $task->getEffortLeft();
    return $timestamp;
  }

  public function getOriginalEstimate() {
    $timestamp = 0;
    foreach($this->getTasks() as $task)
      $timestamp += $task->getOriginalEstimate();
    return $timestamp;
  }

  public function getCurrentEstimate() {
    $timestamp = 0;
    foreach($this->getTasks() as $task)
      $timestamp += $task->getCurrentEstimate();
    return $timestamp;
  }

  public function getEffortSpent() {
    $timestamp = 0;
    foreach($this->getTasks() as $task)
      $timestamp += $task->getEffortSpent();
    return $timestamp;
  }
}