<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Product extends BaseProduct
{
  public function formatName($showComplete) {
    $name = $this->getName();
    
    return $name;
  }
  
  public function getIterations()
  {
    return Doctrine::getTable('Iteration')->findByProduct($this);
  }

  public function getStories()
  {
    return Doctrine::getTable('Story')->findByProduct($this);
  }

  public function getTasks()
  {
    return Doctrine::getTable('Task')->findByProduct($this);
  }

  public function countTasks()
  {
    return Doctrine::getTable('Task')->countByProduct($this);
  }

  public function countAvailableTasks()
  {
    return Doctrine::getTable('Task')->countAvailableByProduct($this);
  }

}