<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Team extends BaseTeam
{
  public function addUser(UserProfile $user) {
    $this->Users[] = $user;
    $this->save();
  }

  public function removeUser(UserProfile $user) {
    $this->unlink('Users', array($user->getId()));
  }

  public function getAvailableUsers() {
    return Doctrine::getTable('sfGuardUser')->findAvailable($this);
  }
}