<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkingUnitTable extends Doctrine_Table
{
  public static function getInstance()
  {
    return Doctrine_Core::getTable('WorkingUnit');
  }

  public function getLastByIteration(Iteration $iteration)
  {
    $q = $this->createQuery('wu')
      ->leftJoin('wu.Task t')
      ->leftJoin('t.Story s')
      ->leftJoin('s.Iteration i')
      ->where('i.id = ?', $iteration->getId())
      ->orderBy('wu.date DESC');

    return $q->fetchOne();
  }

}